### ISSUE TITLE
Thank you very much for this project, does this client support streaming output?

### ISSUE THREAD

**Issue by jiahut** [zweifisch/ollama#3]
This is the output of accessing the API via `curl`
![image](https://github.com/zweifisch/ollama/assets/1067691/938a5da2-e338-4833-81e9-95c181c3e375)

**Comment by s-kostyaev** [comment]
This one support streaming - https://github.com/s-kostyaev/ellama

**Comment by s-kostyaev** [comment]
@jiahut You can try ellama now, it's ready to install.

**Comment by jiahut** [comment]
> @jiahut You can try ellama now, it's ready to install.

Thank you, I will try it later.

**Comment by jiahut** [comment]
@s-kostyaev  
I switched over and found some issues (in the Windows environment). I submitted a [PR](https://github.com/s-kostyaev/ellama/pull/3) and would appreciate it if you could review it when you have time.
